### ISSUE TITLE
How to access ashrae-meteo information?

### ISSUE THREAD

**Issue by viktor-ktorvi** [MHahn37/ashrae-meteo#4]
Hi,

I've tried your code that requests info from the ashrae-meteo website ([here](https://github.com/mj-hahn/ashrae-meteo/blob/bfecf5ea1268fc028eec1394f27a40ee945ad207/ashrae.py#L31)), and it's exactly what I need, but the request doesn't seem to work (I get a response with an error). Do you have any idea how to make this work today?

Thanks!

**Comment by mj-hahn** [comment]
Hello, 

It appears the site has been updated since I originally created this repo.

From an initial look, I can see the request is being formatted differently. You can view the source code here: 

view-source:https://ashrae-meteo.info/v2.0/index.php?lat=43.666&lng=-79.606&place=%27%27&wmo=716240

In particular, the site is making the request here:

```javascript
var params = "lat="+location[0].toFixed(3)+"&long="+location[1].toFixed(3)+"&number="+number_global+"&ashrae_version="+getCookie('ashrae_version');
var request = new ajaxRequest();
request.open("POST", "request_places.php", true);
```

If I have time, I can try to update the script. But if you have time to modify the request and try to fix it, then please send a pull request. Thanks

**Comment by viktor-ktorvi** [comment]
Hey, I conntacted the author of the website and these are the new ways to do it:

```python
url = f"http://ashrae-meteo.info/v2.0/request_places_get.php?lat={latitude}&long={longitude}&number={number}&ashrae_version={ashrae_version}"
```

```python
url = f"http://ashrae-meteo.info/v2.0/request_meteo_parametres_get.php?wmo={wmo}&ashrae_version={ashrae_version}&si_ip=SI"
```

and then just 

```python
resp = requests.get(url)
resp_json = json.loads(resp.text.encode().decode('utf-8-sig'))
```

Thanks for the response, and best of luck if you decide to keep developing.
